exercises(atbash-cipher): implement
exercism/zig pull request #276
Opened 2023-03-27 13:23 UTC by ee7

To-do:

- [x] config.json: decide on exercise order after merging older PRs
- [x] config.json: consider `prerequisites` / `practices`

2023-03-28 09:39 UTC, ErikSchierboom approved these changes

2023-03-28 09:39 UTC, ErikSchierboom commented on exercises/practice/atbash-cipher/.meta/example.zig
> +        'A'...'Z' => 'a' + 'Z' - c,
should this be:

```suggestion
        'A'...'Z' => 'A' + 'Z' - c,
```

2023-08-20 10:28 UTC, booniepepper requested changes

2023-08-20 10:28 UTC, booniepepper commented on exercises/practice/atbash-cipher/test_atbash_cipher.zig
> +    const s = "Testing,1 2 3, testing.";
```suggestion
    const expected = "Gvhgr mt123 gvhgr mt";
    const s = "Testing,1 2 3, testing.";
```

2023-09-18 16:16 UTC, merged